### PR TITLE
B/crate support

### PR DESCRIPTION
**Pull request by bogensberger**

### CODE REVIEW

**Comment by dcelasun** [comment]
Looks nice! But could you please remove https://github.com/crate/sqlpad/commit/eba696f319926fdedcb486c25a54b6ce84bdad5e from the PR? It's doesn't seem relevant for adding Crate support. Also, could you squash the other two commits?

**Comment by bogensberger** [comment]
@dcelasun done :)

**Comment by dcelasun** [comment]
@bogensberger Thanks! LGTM.
@rickbergfalk if you have no objections, I'll go ahead and merge this tonight.

**Comment by rickbergfalk** [comment]
Thanks @bogensberger for the addition and @dcelasun for the merging :) I've published to npm as version 1.12.0

**Pull request merged**
