### PR TITLE
update test name

### PR DESCRIPTION
**Pull request by eladeyal-intel**

### CODE REVIEW

**Comment by rickbergfalk** [comment]
@eladeyal-intel sent you an invite and approved this PR so I'll let you merge 😃

**Comment by eladeyal-intel** [comment]
I don't understand why I get "Some checks haven't completed yet". Did something happen to GitHub actions? should we revert #692 ?

image

**Comment by rickbergfalk** [comment]
I think we need to add on pull request to the actions listened to

```
# Trigger the workflow on push or pull request
on: [push, pull_request]
```

**Comment by rickbergfalk** [comment]
@eladeyal-intel I updated the actions. want to see if pulling them into your branch runs the checks?

**Comment by rickbergfalk** [comment]
@eladeyal-intel will leave this open so you can merge yourself. let me know if that isn't the case.

**Pull request merged**
