### PR TITLE
Support multiple datasets in BigQuery connection

### LINKED ISSUE #587: [bigquery] Multi-dataset schema support
In BigQuery, the top-level unit is a project which can have one or more datasets each of which has one or more tables. This akin to a Postgres database -> schema -> table hierarchy.

@murphyke Is there support for rendering multiple datasets in the side-bar schema and not requiring specifying a dataset in the connection?

### PR DESCRIPTION
**Pull request by bruth**
This tweaks the `datasetName` field to support multiple dataset names
delimited by commas. The result is that all datasets will be rendered in
the schema panel and autocomplete will be available while writing
queries.

Fix #587

Signed-off-by: Byron Ruth <b@devel.io>

### CODE REVIEW

**Comment by bruth** [comment]
This is what it looks like.

Screen Shot 2020-04-10 at 8 52 06 PM

**Comment by rickbergfalk** [comment]
Thanks @bruth!

**Comment by bruth** [comment]
@rickbergfalk Thanks for the review and merge!

**Pull request merged**
