### PR TITLE
Make date localization optional

### LINKED ISSUE #77: Date column types are forcible localized
This is rather annoying in some cases when localization needs to be done through SQL because the date output is by day and not hour (which is required to properly localize). Can this be made into an option?

### PR DESCRIPTION
**Pull request by dlabey**
Fixes #77

### CODE REVIEW

**Comment by rickbergfalk** [comment]
Thanks @dlabey! I'll get this published to npm this weekend.

**Comment by dlabey** [comment]
@rickbergfalk did this get updated? I am not seeing it

**Comment by rickbergfalk** [comment]
Sorry it did not - publishing now

**Comment by rickbergfalk** [comment]
@dlabey 1.14.0 is now on npm

**Comment by dlabey** [comment]
Awesome thank you!

**Pull request merged**
