### PR TITLE
Auto connection

### PR DESCRIPTION
**Pull request by eladeyal-intel**
Hide connection menu and auto-select if there's only one option - i.e. an editor with exactly 1 connection

### CODE REVIEW

**Comment by eladeyal-intel** [comment]
Ready for review and merge I guess. Ref #660

**Comment by rickbergfalk** [comment]
Can we put this in initApp instead? https://github.com/rickbergfalk/sqlpad/blob/master/client/src/stores/initApp.js

**Comment by eladeyal-intel** [comment]
1. Even if we do move the selection to initApp, the decision to render or hide the ConnectionDropdown should stay in ConnectionDropdown.js right?

2. My initial proposal would have editors get the auto-selected connection; and admins would still get the "...select connection" since they can use the dropdown to select "New connection". If want to implement the same distinction while auto-selection in initApp.js, then information about the current user should be delivered into initApp.js. I don't know how to do it (and if it's possible).

3. We can auto-select automatically for admins as well, then it may be a bit confusing because the admin will see a selected connection but he can still use the dropdown for other activities.

**Comment by eladeyal-intel** [comment]
I modified to auto select connection to all users

**Comment by rickbergfalk** [comment]
Oh yeah. sorry my initial message wasn't clear. The auto-selecting can go into initApp and happen for all. For hiding the connection picker, I'm open to hiding it for everyone, or just non-admins. I thought it'd be nice to create connections from the drop down, but I realize too that it is maybe an anti-pattern and not a frequent action.

**Pull request merged**
