### PR TITLE
Fix MSSQL JSON and queries list API

### PR DESCRIPTION
**Pull request by rickbergfalk**
Adds work around for lack of proper JSON support in SQL Server. 

While the JSON datatype can be added to SQL Server as a string, Sequelize does not parse that string to an object. As a solution, the field checked and parsed in application code after the fact. 

This isn't great, but it works for now.

This also fixes a SQL incompatibility in the queries list API route to address the fact that SQL Server does not support LIMIT/OFFSET.

### CODE REVIEW

**Comment by rickbergfalk** [comment]
@eladeyal-intel I'm seeing duplicate actions being run on my end for both push and pull_request triggers. 

Looks like others hit this https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/2

Do you see any issue changing this to pull_request only or potentially adding the if-check on repo name?

**Comment by eladeyal-intel** [comment]
I'm not very exipirnces with github actions. In #736 I tried to do what you suggested - let's see if it helps.

**Comment by rickbergfalk** [comment]
@eladeyal-intel yeah I was thinking about that and the switch to PR only.

**Comment by rickbergfalk** [comment]
I think mssql might be green now 🤞

**Comment by eladeyal-intel** [comment]
👏

**Pull request merged**
