### PR TITLE
updated to use sequelize v. 5.22.0

### PR DESCRIPTION
**Pull request by yorek**
Fix for #705

### CODE REVIEW

**Comment by rickbergfalk** [comment]
@yorek instead of manually changing `package.json` can you run `npm update sequelize` in the server directory? The `package-lock.json` also needs updating

**Comment by yorek** [comment]
Will do. Sorry I'm a Node newbie :)

**Comment by rickbergfalk** [comment]
No worries! Appreciate taking the time to open a PR :)

**Comment by rickbergfalk** [comment]
And realize my original comment maybe wasn't clear - using `npm update` will manage `package-lock.json` automatically

**Comment by yorek** [comment]
Thanks Rick. I'm trying to update but it seems there are issues with NPM and WSL2. I'm also having quite a lot of error using Windows 10. I'll need to spin up a Ubuntu machine.

**Comment by yorek** [comment]
Done, now both package.json and package-lock.json are updated

**Comment by rickbergfalk** [comment]
Thanks @yorek!

**Pull request merged**
