### PR TITLE
Fix that docker image could not be built from a clean repo

### PR DESCRIPTION
**Pull request by jmagnusson**
This allows for Docker hub automated builds to run. See [hub.docker.com/r/jacobsvante/sqlpad](https://hub.docker.com/r/jacobsvante/sqlpad) for an example.

The PR also includes:

* Upgrade to `node:12.3.1-alpine`
* Graceful shutdowns of server (`SIGINT` and `SIGTERM`)
* Remove dependency on bash in `scripts/build.sh`
* Move Dockerfile up to project directory, as that's the standard location to put the file in (plus it now depends on `scripts/build.sh` which is not inside the `server/` dir)

Some minor details:

- I've removed the `ENV DEBIAN_FRONTEND noninteractive` dockerfile instruction. We're running in Alpine so I don't think this one's necessary.
- I've removed the `server/docker-publish.sh` command as it's not really needed now that we can do automated builds.

### CODE REVIEW

**Comment by jmagnusson** [comment]
An improvement that could be made in the future is to autobuild images that includes odbc support as well. However I'm getting build errors with [odbc@1.4.6](https://www.npmjs.com/package/odbc/v/1.4.6).

[2.0.0-beta.1](https://www.npmjs.com/package/odbc/v/2.0.0-beta.1) seems to build just fine in the alpine image:
```Dockerfile
RUN apk add --no-cache make g++ unixodbc-dev python-dev && npm install odbc@beta
```

I've not done any testing with that though.

**Comment by seerwright** [comment]
Thanks for this. I gave it a try with `docker build -t sqlpad .` against your proposed branch and ran into node-gyp issues. I'm not sure if this is noise or if it is helpful, but my hope is to build a sqlpad docker image and I'm finding it quite difficult - perhaps due to some wrong action by me. 

Anyway, here is an excerpt of the build steps around node-gyp configuration. I stumbled upon this PR while trying to address this same issue (seemingly) from Master. I've tried setting PYTHON and PYTHONPATH as well as other things in the build. I'm a node dummy, so a bit out of my element with the npm build processes. 
 
```
Step 6/7 : RUN scripts/build.sh &&     npm cache clean --force &&     cp -r /sqlpad/server /usr/app &&     cp /sqlpad/docker-entrypoint / &&     chmod +x /docker-entrypoint &&     rm -rf /sqlpad
 ---> Running in cae63b28b7fa
added 0 packages in 0.032s

> fsevents@1.2.8 install /sqlpad/client/node_modules/chokidar/node_modules/fsevents
> node install


> fsevents@1.2.8 install /sqlpad/client/node_modules/jest-haste-map/node_modules/fsevents
> node install

added 1508 packages in 19.258s

> odbc@1.4.5 install /sqlpad/server/node_modules/odbc
> node-gyp configure build

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.3.1 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:149:21)
gyp ERR! System Linux 4.19.34-04457-g5b63d4390e96
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /sqlpad/server/node_modules/odbc
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
added 278 packages in 5.057s

> sqlpad-front-end@0.1.0 build /sqlpad/client
> react-scripts build

Creating an optimized production build...
```

**Comment by rickbergfalk** [comment]
Thanks a bunch for this @jmagnusson! This was on my todo list once I finished UI changes. I've held off since the UI is in a weird state right now, but maybe that's okay for the "latest" tag?

@seerwright that should just be noise, and the resulting image should be functional. 

I'm all for adding python and other necessary dependencies to allow for odbc to be included as well.

**Comment by jmagnusson** [comment]
Awesome! Looking forward to the UI fixes 😀

**Pull request merged**
