### PR TITLE
Implement Vertica support

### PR DESCRIPTION
**Pull request by dcelasun**
Hi,

This PR adds support for the Vertica analytics database. I didn't introduce any new dependencies as Vertica can also work through the PostgreSQL protocol. The only thing that required modification was the information schema query as Vertica has a distinct metadata format.

Tested with latest stable Vertica 7.x.

### CODE REVIEW

**Comment by rickbergfalk** [comment]
This is awesome - thanks @dcelasun! I'll aim to publish an updated sqlpad to npm sometime this weekend.

**Comment by dcelasun** [comment]
I'm glad you like it! sqlpad is exactly what we are looking for our internal network, so I'm happy to contribute :)

**Comment by rickbergfalk** [comment]
@dcelasun Vertica support has been published to npm. Really excited about the expanded support and thrilled to hear your team is getting some use out of it. 

Let me know if you'd like to be added as a contributor to the project or have commit rights - you're more than welcome.

**Comment by dcelasun** [comment]
@rickbergfalk Thanks, I'd love to contribute more. We have a few more features in mind, so becoming a contributor and having commit rights would be great! I will of course discuss things with you before pushing anything :)

**Comment by rickbergfalk** [comment]
great! I'll get you added

**Pull request merged**
