### PR TITLE
 enable drag to view column cell content

### PR DESCRIPTION
**Pull request by KochamCie**
enable drag to view column cell content

### CODE REVIEW

**Comment by KochamCie** [comment]
e'm'm
my friend found when the result cell content is large while the div element can't move to see detail.
even though I can change the column width .

so i play a trick =0=

**Comment by rickbergfalk** [comment]
haha ok I'll try this out :)

Any idea why past commits already merged are showing up in your PR? Have you pulled latest from sqlpad master?

**Comment by KochamCie** [comment]
I'm weird, too  ：（

**Comment by rickbergfalk** [comment]
Sorry for the delay in getting back to you! I tried your branch out and it is indeed a creative solution :)

Unfortunately though it loses styling...

What do you think about having a button on each row to see a popup of all the rows results? That way long text could be viewed all at once?

**Comment by KochamCie** [comment]
i just found a great bug in this solution.hah
so i'm going to close it
your idea was my first thought~  but my css skill is poor

**Pull request closed without merging**
